### ISSUE TITLE
Order of random token replacement and mask filling

### ISSUE THREAD

**Issue by qibinc** [lucidrains/mlm-pytorch#6]
HI @lucidrains ,

Thanks for the great work on this repo. I found something that might cause unexpected behavior in the following code:

https://github.com/lucidrains/mlm-pytorch/blob/3e811481a996f712e321165a9e78750a459ab528/mlm_pytorch/mlm_pytorch.py#L75-L88

The original paper use a 80% (mask), 10% (random word replacement), 10% (unchanged) combination. In this implementation, however, most of the random word replacement (the probability of this intersection is `random_token_prob * replace_prob`) on Line 83 will be overwritten by the mask filling on line 87.

**Comment by lucidrains** [comment]
@qibinc Hi Qibin! Thank you for catching this, I believe you are correct

Can you check to see if 0.1.0 fixes things for you? https://github.com/lucidrains/mlm-pytorch/blob/0.1.0/mlm_pytorch/mlm_pytorch.py#L92

**Comment by qibinc** [comment]
Hi @lucidrains , thanks for the fix! Overall it LGTM, with a minor issue:

The expected behavior (as in the paper) should be:

```
80% (replace_prob - random_token_prob): word -> [MASK]
10% (random_token_prob): word -> random
10% (1 - replace_prob): word -> word
```
when `replace_prob=0.9` and `random_token_prob=0.1`

With the current code after the fix, the behavior is:

```
10% (random_token_prob): word -> random
81% (1 - random_token_prob) * replace_prob: word -> [MASK]
9%  (1 - random_token_prob) * (1 - replace_prob): word -> word
```

I personally don't think this will affect the performance at all, but putting the calculation here if someone cares in the future :)

**Comment by lucidrains** [comment]
Yes you are absolutely correct :D close enough was what I thought, but perhaps I'll fix it properly next week! Thank you for catching this!
